### ISSUE TITLE
Podkład czarno-biała nie działa

### ISSUE THREAD

**Issue by starsep** [Ancymonek/powOsm#13]
Pewnie warto schować lub znaleźć alternatywę
![image](https://user-images.githubusercontent.com/2798728/193416681-09e1f6d3-557c-4e5a-b8d9-e61f55404bde.png)

**Comment by Ancymonek** [comment]
Dzięki za zgłoszenie, usunąłem tę warstwę:
![obraz](https://user-images.githubusercontent.com/16021640/212125296-00e2c76f-28ba-42fd-bfb2-a97961e4d99d.png)
