### ISSUE TITLE
drobne błędy językowe

### ISSUE THREAD

**Issue by maro-21** [Ancymonek/powOsm#15]
- "Dostępność dla niepełnosprawnych: ograniczone" - jak dostępność, to "ograniczonA".
- "strona internetowa: witryna" - jakoś mi to nie pasuje, ale nie wiem na co zmienić.

**Comment by Ancymonek** [comment]
Dzięki za zgłoszenia:

![obraz](https://user-images.githubusercontent.com/16021640/212124255-3ed3f524-6ea6-42e9-a962-22c807a37896.png)
![obraz](https://user-images.githubusercontent.com/16021640/212124303-b8b5b72e-1bd9-4c62-97fc-bd52b07ad72a.png)

Poprawione.
