### ISSUE TITLE
adresy z addr:place

### ISSUE THREAD

**Issue by maro-21** [Ancymonek/powOsm#16]
Adres podawany w sekcji "Adres", w przypadku gdy nie jest to adres z `addr:street` + `addr:city`, tylko z `addr:place` powinien wyglądać:
`addr:place` `addr:housenumber`, `addr:postcode` `addr:place`
a obecnie jest:
`addr:housenumber`, `addr:postcode` `addr:place`

Przykład:
https://plname.usermd.net/#map=13/51.1675/21.15452,w252790899

**Comment by Ancymonek** [comment]
Poprawione:
![obraz](https://user-images.githubusercontent.com/16021640/212534587-6078cc96-4fc4-4e1d-97de-d0d001309a69.png)

Mogą być jeszcze jakieś nieobsłużone skrajne przypadki ale myślę, że większość jest obsłużona a resztę trzeba poprawić w danych na mapie.
