### ISSUE TITLE
Brak crypto-js.min.js

### ISSUE THREAD

**Issue by starsep** [Ancymonek/powOsm#8]
Po zainstalowaniu pakietu [crypto-js z npma](https://www.npmjs.com/package/crypto-js) nie mam pliku crypto-js.min.js, jest tylko crypto-js.js

Problem nie występuję na stronie, tylko lokalnie. https://plname.usermd.net/static/node_modules/crypto-js/crypto-js.min.js jest dostępny

**Comment by Ancymonek** [comment]
Teraz wychodzą moje zahardkodowane rzeczy :P Zajmę się tym jak uporam się z uruchomieniem mongo w kontenerze, bo teraz mam przy tworzeniu taki błąd https://github.com/docker-library/mongo/issues/323.

**Comment by starsep** [comment]
> teraz mam przy tworzeniu taki błąd [docker-library/mongo#323](https://github.com/docker-library/mongo/issues/323).

Wydaje mi się, że też miałem ten problem (lub podobny), ale wszystko działało. Postaram się potem postawić od zera i zobaczyć czy umiem powtórzyć oraz czy to realny problem.

**Comment by Ancymonek** [comment]
przy tworzeniu mongo:
`Successfully added user: {
"user" : "root",
"roles" : [
{
"role" : "root",
"db" : "admin"
}
]
}
Error saving history file: FileOpenFailed Unable to open() file /home/mongodb/.dbshell: No such file or directory
{"t":{"$date":"2021-01-23T14:02:42.218+00:00"},"s":"I", "c":"NETWORK", "id":22944, "ctx":"conn2","msg":"Connection ended","attr":`

a później:
`{"t":{"$date":"2021-01-23T14:09:36.759+00:00"},"s":"I", "c":"ACCESS", "id":20249, "ctx":"conn6","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-1","principalName":"root","authenticationDatabase":"powosm","client":"172.20.0.3:51598","result":"UserNotFound: Could not find user \"root\" for db \"powosm\""}}`

a w logach kontenera pythonowego mam:
`pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}`

**Comment by starsep** [comment]
> przy tworzeniu mongo:
> `Successfully added user: { "user" : "root", "roles" : [ { "role" : "root", "db" : "admin" } ] }
> 
> a później:
> UserNotFound: Could not find user \"root\" for db \"powosm\""}}
> 
> a w logach kontenera pythonowego mam:
> `pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}`

Ten błąd też miałem, myślałem, że się udało naprawić 😢 Może to być kwestia bazy danych admin vs powosm

**Comment by starsep** [comment]
To issue zostało naprawione przez https://github.com/Ancymonek/powOsm/commit/3ea6541bb69586a087cb0ce241ac618e9efdf60b i potem crypto-js zostało zastąpione w https://github.com/Ancymonek/powOsm/commit/68cfdab94a3f7fb355839bd971417ae1f2704f8d

Jeżeli chodzi o problemy z mongo to postaram się potem potwierdzić na innym komputerze "na czysto",  gdzie na pewno nie mam związanych z tym projektem obrazów Dockera, volume'ów itp.

**Comment by starsep** [comment]
> Jeżeli chodzi o problemy z mongo to postaram się potem potwierdzić na innym komputerze "na czysto", gdzie na pewno nie mam związanych z tym projektem obrazów Dockera, volume'ów itp.

U mnie działa :), w razie problemów pisz, spróbuję pomóc

**Comment by Ancymonek** [comment]
Ok, jutro po pracy pousuwam wszelkie dockery i zainstaluje ponownie, może coś pomoże :)

**Comment by Ancymonek** [comment]
Po reinstalacjach dalej to samo. Coś nie może u mnie utworzyć usera ;(

**Comment by Ancymonek** [comment]
Udało mi się to zrobić, ale dopiero po zmianie pliku mongo-init.sh na plik js i z zahardkodowanymi userem, hasłem i bazą. Zrobię commita z tymi nowymi ustawieniami, żebyś mógł zobaczyć u siebie.

**Comment by starsep** [comment]
Przetestowałem na jeszcze kolejnym komputerze aktualnego mastera i działa - imho sukces :)
Basha wybrałem, aby móc użyć zmiennych środowiskowych, ale na tę chwilę i tak były zhardkodowane w docker-compose.yml
