### ISSUE TITLE
Brak layers.png

### ISSUE THREAD

**Issue by starsep** [Ancymonek/powOsm#9]
Strona próbuje wczytać plik https://plname.usermd.net/images/layers.png
Nie jest on dostępny - występuje zarówno na stronie oraz lokalnie

**Comment by Ancymonek** [comment]
Hmm, nie umiem tego odtworzyć, weryfikowałem lokalnie i na dockerze i wszystko działa. Jakieś szczegóły?

**Comment by starsep** [comment]
Wygląda, że wszystko działa, ale Firefox próbuje wczytać ten obrazek
![image](https://user-images.githubusercontent.com/2798728/105868261-49390800-5ff6-11eb-8fc2-09553b23e056.png)

Stacktrace:
_updateLevels GridLayer.js:395:3
_setView GridLayer.js:566:8
_resetView GridLayer.js:526:7
onAdd GridLayer.js:162:7
_layerAdd Layer.js:114:7
whenReady Map.js:1465:12
addLayer Layer.js:176:7
addTo Layer.js:52:6
`<anonymous>` https://plname.usermd.net/static/js/map.js:86:5

**Comment by Ancymonek** [comment]
Odtworzyłem ten błąd, gdy dodałem cssy do bundle'a, poprawiłem to tymczasowo w CSS-ie, docelowo będzie inna ikonka ;p
